apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: n73s2o3vb-nodejs 
  janus-idp.io/tekton: n73s2o3vb-nodejs
  backstage.io/kubernetes-id: n73s2o3vb-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: n73s2o3vb-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml